## START COPYRIGHT NOTICE ##
# AmazonLinux2-CIS Ansible Script
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
## END COPYRIGHT NOTICE ##
- name: "NOTSCORED | 2.1.1.1 | PATCH | Ensure time synchronization is in use - service install"
  yum:
      name: "{{ amazonlinux2cis_time_synchronization }}"
      state: present
  tags:
    - level1
    - patch
    - rule_2.1.1.1
    - low

- name: "NOTSCORED | 2.2.1.1 | PATCH | Ensure time synchronization is in use - service start"
  systemd:
      name: "{{ amazonlinux2cis_time_synchronization }}d"
      state: started
      enabled: yes
  ignore_errors: true
  tags:
    - level1
    - patch
    - rule_2.1.1.1
    - low

- name: "NOTSCORED | 2.1.1.1 | PATCH | Ensure time synchronization is in use - service stop ntp"
  systemd:
    name: ntpd
    state: stopped
    enabled: no
  ignore_errors: true
  when:
    - amazonlinux2cis_time_synchronization is defined
    - amazonlinux2cis_time_synchronization == "chrony" and ntpd_service_status.stdout == "loaded"
  tags:
    - level1
    - patch
    - rule_2.1.1.1
    - low

- name: "NOTSCORED | 2.1.1.1 | PATCH | Ensure time synchronization is in use - service stop chrony"
  systemd:
    name: chronyd
    state: stopped
    enabled: no
  ignore_errors: yes
  when: 
    - amazonlinux2cis_time_synchronization is defined
    - amazonlinux2cis_time_synchronization == "ntp" and chronyd_service_status.stdout == "loaded"
  tags:
    - level1
    - patch
    - rule_2.1.1.1
    - low

- name: "SCORED | 2.1.1.2 | PATCH | Ensure ntp is configured | modify /etc/ntp.conf"
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  when:
    - amazonlinux2cis_time_synchronization is defined
    - amazonlinux2cis_time_synchronization == "ntp"
  tags:
    - level1
    - patch
    - rule_2.1.1.2
    - low

- name: "SCORED | 2.1.1.2 | PATCH | Ensure ntp is configured | modify /etc/sysconfig/ntpd"
  lineinfile:
    dest: /etc/init.d/ntpd
    regexp: "^(#)?(\\s)*?daemon\\s\\$prog"
    line: "daemon $prog -u ntp:ntp -p /var/run/ntpd.pid $OPTIONS"
  when:
    - amazonlinux2cis_time_synchronization is defined
    - amazonlinux2cis_time_synchronization == "ntp"
  tags:
    - level1
    - patch
    - rule_2.1.1.2
    - low

- name: "SCORED | 2.1.1.3 | PATCH | Ensure chrony is configured"
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
  when:
    - amazonlinux2cis_time_synchronization is defined
    - amazonlinux2cis_time_synchronization == "chrony"
  tags:
    - level1
    - patch
    - rule_2.1.1.3
    - low

- name: "SCORED | 2.1.1.3 | PATCH | Ensure chrony is configured | modify /etc/sysconfig/chronyd"
  lineinfile:
    dest: /etc/sysconfig/chronyd
    regexp: "^(#)?OPTIONS"
    line: "OPTIONS=\"-u chrony\""
    state: present
    create: yes
  when:
    - amazonlinux2cis_time_synchronization is defined
    - amazonlinux2cis_time_synchronization == "chrony"
  tags:
    - level1
    - patch
    - rule_2.1.1.3
    - low

- name: "SCORED | 2.1.2 | PATCH | Ensure X Window System is not installed"
  yum:
    name: "{{item}}"
    state: absent
  when:
    - not amazonlinux2cis_xwindows_required
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  with_items:
    - "@X Window System"
    - "xorg-x11*"
  tags:
    - level1
    - scored
    - xwindows
    - patch
    - rule_2.1.2
    - low
    - disable_service_checks

- name: "SCORED | 2.1.3 | PATCH | Ensure Avahi Server is not enabled"
  service:
    name: avahi-daemon
    state: stopped
    enabled: no
  ignore_errors: yes
  when:
    - (not amazonlinux2cis_avahi_server and avahi_service_status.stdout == "loaded")
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - scored
    - avahi
    - services
    - patch
    - rule_2.1.3
    - low
    - disable_service_checks

- name: "SCORED | 2.1.4 | PATCH | Ensure CUPS is not enabled"
  systemd:
    name: cups
    state: stopped
    enabled: no
  ignore_errors: yes
  when:
    - (not amazonlinux2cis_cups_server == false and cups_service_status.stdout == "loaded")
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - scored
    - cups
    - services
    - patch
    - rule_2.1.4
    - low
    - disable_service_checks

- name: "SCORED | 2.1.5 | PATCH | Ensure DHCP Server is not enabled"
  systemd:
    name: dhcpd
    state: stopped
    enabled: no
  ignore_errors: yes
  when:
    - (not amazonlinux2cis_dhcp_server and dhcpd_service_status.stdout == "loaded")
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - scored
    - dhcp
    - services
    - patch
    - rule_2.1.5
    - low
    - disable_service_checks

- name: "SCORED | 2.1.6 | PATCH | Ensure LDAP server is not enabled"
  systemd:
    name: slapd
    state: stopped
    enabled: no
  ignore_errors: yes
  when:
    - (not amazonlinux2cis_ldap_server and slapd_service_status.stdout == "loaded")
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - scored
    - ldap
    - services
    - patch
    - rule_2.1.6
    - low
    - disable_service_checks

- name: "SCORED | 2.1.7 | PATCH | Ensure NFS and RPC are not enabled"
  systemd:
    name: nfs
    state: stopped
    enabled: no
  ignore_errors: yes
  when:
    - (not amazonlinux2cis_nfs_rpc_server and nfs_service_status.stdout == "loaded")
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - scored
    - nfs
    - rpc
    - services
    - patch
    - rule_2.1.7
    - low
    - disable_service_checks

- name: "SCORED | 2.1.7 | PATCH | Ensure NFS and RPC are not enabled"
  systemd:
    name: rpcbind
    state: stopped
    enabled: no
  ignore_errors: yes
  when:
    - (not amazonlinux2cis_nfs_rpc_server and rpcbind_service_status.stdout == "loaded")
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - scored
    - nfs
    - rpc
    - services
    - patch
    - rule_2.1.7
    - low
    - disable_service_checks

- name: "SCORED | 2.1.8 | PATCH | Ensure DNS Server is not enabled"
  systemd:
    name: named
    state: stopped
    enabled: no
  ignore_errors: yes
  when:
    - (not amazonlinux2cis_named_server and named_service_status.stdout == "loaded")
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - patch
    - rule_2.1.8
    - low
    - disable_service_checks

- name: "SCORED | 2.1.9 | PATCH | Ensure FTP Server is not enabled"
  systemd:
    name: vsftpd
    state: stopped
    enabled: no
  ignore_errors: yes
  when:
    - (not amazonlinux2cis_vsftpd_server and vsftpd_service_status.stdout == "loaded")
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - patch
    - rule_2.1.9
    - low
    - disable_service_checks

- name: "SCORED | 2.1.10 | PATCH | Ensure HTTP server is not enabled"
  systemd:
    name: httpd
    state: stopped
    enabled: no
  ignore_errors: yes
  when:
    - (not amazonlinux2cis_httpd_server and httpd_service_status.stdout == "loaded")
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - patch
    - rule_2.1.10
    - low
    - disable_service_checks

- name: "SCORED | 2.1.11 | PATCH | Ensure IMAP and POP3 server is not enabled"
  systemd:
    name: dovecot
    state: stopped
    enabled: no
  ignore_errors: yes
  when:
    - (not amazonlinux2cis_dovecot_server and dovecot_service_status.stdout == "loaded")
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - patch
    - rule_2.1.11
    - low
    - disable_service_checks

- name: "SCORED | 2.1.12 | PATCH | Ensure Samba is not enabled"
  systemd:
    name: smb
    state: stopped
    enabled: no
  ignore_errors: yes
  when:
    - (not amazonlinux2cis_smb_server and smb_service_status.stdout == "loaded")
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - patch
    - rule_2.1.12
    - low
    - disable_service_checks

- name: "SCORED | 2.1.13 | PATCH | Ensure HTTP Proxy Server is not enabled"
  systemd:
    name: squid
    state: stopped
    enabled: no
  ignore_errors: yes
  when:
    - (not amazonlinux2cis_squid_server and squid_service_status.stdout == "loaded")
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - patch
    - rule_2.1.13
    - low
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks

- name: "SCORED | 2.1.14 | PATCH | Ensure SNMP Server is not enabled"
  systemd:
    name: snmpd
    state: stopped
    enabled: no
  ignore_errors: yes
  when: 
    - (not amazonlinux2cis_snmp_server and snmpd_service_status.stdout == "loaded")
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - patch
    - rule_2.1.14
    - low
    - disable_service_checks

- name: "SCORED | 2.1.15 | PATCH | Ensure mail transfer agent is configured for local-only mode"
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^(#)?inet_interfaces"
    line: "inet_interfaces = localhost"
  when: 
    - (not amazonlinux2cis_is_mail_server and postfix_installed.rc == 0)
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - patch
    - rule_2.1.15
    - low
    - disable_service_checks

- name: "SCORED | 2.1.16 | PATCH | Ensure NIS Server is not enabled"
  systemd:
    name: ypserv
    state: stopped
    enabled: no
  ignore_errors: yes
  when: 
    - (not amazonlinux2cis_nis_server and ypserv_service_status.stdout == "loaded")
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - patch
    - rule_2.1.16
    - low
    - disable_service_checks

- name: "SCORED | 2.1.17 | PATCH | Ensure rsh server is not enabled | rsh"
  systemd:
    name: rsh.socket
    state: stopped
    enabled: no
  ignore_errors: true
  when: 
    - (not amazonlinux2cis_rsh_server == false and rsh_service_status.stdout == "loaded")
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - patch
    - rule_2.1.17
    - low
    - disable_service_checks

- name: "SCORED | 2.1.17 | PATCH | Ensure rsh server is not enabled | rlogin"
  systemd:
    name: rlogin.socket
    state: stopped
    enabled: no
  ignore_errors: true
  when: 
    - (not amazonlinux2cis_rsh_server and rlogin_service_status.stdout == "loaded")
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - patch
    - rule_2.1.17
    - low
    - disable_service_checks

- name: "SCORED | 2.1.17 | PATCH | Ensure rsh server is not enabled | rexec"
  systemd:
    name: rexec.socket
    state: stopped
    enabled: no
  ignore_errors: true
  when: 
    - (not amazonlinux2cis_rsh_server and rexec_service_status.stdout == "loaded")
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - patch
    - rule_2.1.17
    - low
    - disable_service_checks

- name: "SCORED | 2.1.17 | PATCH | Ensure rsh server is not enabled | rexec"
  stat:
    path: /etc/xinetd.d/rexec
  register: rexec_service
  tags:
    - level1
    - scored
    - patch
    - rule_2.1.17
    - low

- name: "SCORED | 2.1.17 | PATCH | Ensure rsh server is not enabled | rexec"
  systemd:
    name: rexec.socket
    state: stopped
    enabled: no
  ignore_errors: true
  when: 
    - (rexec_service is defined and rexec_service.stat.exists and not amazonlinux2cis_rsh_server)
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - scored
    - patch
    - rule_2.1.17
    - low
    - disable_service_checks

# - name: "SCORED | 2.1.17 | PATCH | Ensure rsh server is not enabled | rlogin"
#   stat:
#     path: /etc/xinetd.d/rlogin
#   register: rlogin_service
#   tags:
#     - level1
#     - scored
#     - patch
#     - rule_2.1.17
#     - low

# - name: "SCORED | 2.1.17 | PATCH | Ensure rsh server is not enabled | rlogin"
#   command: chkconfig rlogin off
#   notify: restart rsh-server
#   when: rlogin_service.stat.exists
#   tags:
#     - level1
#     - scored
#     - patch
#     - rule_2.1.17
#     - low

# - name: "SCORED | 2.1.17 | PATCH | Ensure rsh server is not enabled | rsh"
#   stat:
#       path: /etc/xinetd.d/rsh
#   register: rsh_service
#   tags:
#     - level1
#     - scored
#     - patch
#     - rule_2.1.17
#     - low

# - name: "SCORED | 2.1.17 | PATCH | Ensure rsh server is not enabled | rsh"
#   command: chkconfig rsh off
#   notify: restart rsh-server
#   when: rsh_service.stat.exists
#   tags:
#     - level1
#     - scored
#     - patch
#     - rule_2.1.17
#     - low

- name: "SCORED | 2.1.18 | PATCH | Ensure telnet server is not enabled"
  systemd:
    name: telnet
    state: stopped
    enabled: no
  ignore_errors: true
  when: 
    - (not amazonlinux2cis_telnet_server and telnet_service_status.stdout == "loaded")
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - patch
    - rule_2.1.18
    - low
    - disable_service_checks

- name: "SCORED | 2.1.19 | PATCH | Ensure tftp server is not enabled"
  systemd:
    name: tftp
    state: stopped
    enabled: no
  ignore_errors: yes
  when: 
    - (not amazonlinux2cis_tftp_server and tftp_service_status.stdout == "loaded")
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - scored
    - insecure_services
    - tftp
    - patch
    - rule_2.1.19
    - low
    - disable_service_checks

- name: "SCORED | 2.1.20 | PATCH | Ensure rsync service is not enabled "
  systemd:
    name: rsyncd
    state: stopped
    enabled: no
  ignore_errors: true
  when: 
    - (not amazonlinux2cis_rsyncd_server and rsyncd_service_status.stdout == "loaded")
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - patch
    - rule_2.1.20
    - low
    - disable_service_checks

- name: "SCORED | 2.1.21 | PATCH | Ensure talk server is not enabled"
  systemd:
    name: ntalk
    state: stopped
    enabled: no
  ignore_errors: yes
  when: 
    - (not amazonlinux2cis_ntalk_server and ntalk_service_status.stdout == "loaded")
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - patch
    - rule_2.1.21
    - low
    - disable_service_checks

- name: "SCORED | 2.2.1 | PATCH | Ensure NIS Client is not installed"
  yum:
    name: ypbind
    state: absent
  when: 
    - (not amazonlinux2cis_ypbind_required)
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - patch
    - rule_2.2.1
    - low
    - disable_service_checks

- name: "SCORED | 2.2.2 | PATCH | Ensure rsh client is not installed"
  yum:
    name: rsh
    state: absent
  when: 
    - (not amazonlinux2cis_rsh_required)
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - patch
    - rule_2.2.2
    - low
    - disable_service_checks

- name: "SCORED | 2.2.3 | PATCH | Ensure talk client is not installed"
  yum:
    name: talk
    state: absent
  when: 
    - (not amazonlinux2cis_talk_required)
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - patch
    - rule_2.2.3
    - low
    - disable_service_checks

- name: "SCORED | 2.2.4 | PATCH | Ensure telnet client is not installed"
  yum:
    name: telnet
    state: absent
  when: 
    - (not amazonlinux2cis_telnet_required)
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - patch
    - rule_2.2.4
    - low
    - disable_service_checks

- name: "SCORED | 2.2.5 | PATCH | Ensure LDAP client is not installed"
  yum:
    name: openldap-clients
    state: absent
  when: 
    - (not amazonlinux2cis_openldap_clients_required)
    - amazonlinux2cis_disable_service_checks is defined and amazonlinux2cis_disable_service_checks
  tags:
    - level1
    - patch
    - rule_2.2.5
    - low
    - disable_service_checks