## COPYRIGHT NOTICE - LICENSED UNDER GNU GPLV3 ##
## START COPYRIGHT NOTICE ##
# AmazonLinux2-CIS Ansible Script - Under Joint Copyright
# Copyright (C) 2019  RADSec
# Copyright (C) 2019  Glownew Group

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
## END COPYRIGHT NOTICE ##
- name: "NOTSCORED | 4.1.1.1 | PATCH | Ensure audit log storage size is configured"
  lineinfile:
    dest: /etc/audit/auditd.conf
    regexp: "^max_log_file"
    line: "max_log_file = 10"
    state: present
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.1.1
    - low

- name: "SCORED | 4.1.1.2 | PATCH | Ensure system is disabled when audit logs are full"
  lineinfile:
    dest: /etc/audit/auditd.conf
    regexp: "^admin_space_left_action"
    line: "admin_space_left_action = halt"
    state: present
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.1.2
    - low

- name: "SCORED | 4.1.1.2 | PATCH | Ensure system is disabled when audit logs are full"
  lineinfile:
    dest: /etc/audit/auditd.conf
    regexp: "^space left action"
    line: "space left action = email"
    state: present
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.1.2
    - low

- name: "SCORED | 4.1.1.2 | PATCH | Ensure system is disabled when audit logs are full"
  lineinfile:
    dest: /etc/audit/auditd.conf
    regexp: "^action mail acct"
    line: "action mail acct = root"
    state: present
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.1.2
    - low

- name: "SCORED | 4.1.1.3 | PATCH | Ensure audit logs are not automatically deleted"
  lineinfile:
    dest: /etc/audit/auditd.conf
    regexp: "^max_log_file_action"
    line: "max_log_file_action = keep_logs"
    state: present
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.1.3
    - low

- name: "SCORED | 4.1.2 | PATCH | Ensure auditd service is enabled"
  service:
    name: auditd
    state: started
    enabled: yes
  when: amazonlinux2cis_enable_auditd
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.2
    - low

- name: "SCORED | 4.1.3 | PATCH | Ensure auditing for processes that start prior to auditd is enabled"
  replace:
    dest: /etc/default/grub
    regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!audit=1)(?:")'
    replace: '\1"\2 audit=1"'
    follow: yes
  ignore_errors: yes
  notify: generate new grub config
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.3
    - low

- name: "SCORED | 4.1.4 | PATCH | Ensure events that modify date and time information are collected"
  blockinfile:
    path: /etc/audit/audit.rules
    state: present
    create: yes
    block: "-a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time-change\n
            -a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k timechange\n
            -a always,exit -F arch=b64 -S clock_settime -k time-change\n
            -a always,exit -F arch=b32 -S clock_settime -k time-change\n
            -w /etc/localtime -p wa -k time-change"
  ignore_errors: yes
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.4
    - low

- name: "SCORED | 4.1.5 | PATCH | Ensure events that modify user/group information are collected"
  blockinfile:
    path: /etc/audit/rules.d/audit.rules
    state: present
    create: yes
    block: "-w /etc/group -p wa -k identity\n
            -w /etc/passwd -p wa -k identity\n
            -w /etc/gshadow -p wa -k identity\n
            -w /etc/shadow -p wa -k identity\n
            -w /etc/security/opasswd -p wa -k identity"
  ignore_errors: yes
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.5
    - low

- name: "SCORED | 4.1.6 | PATCH | Ensure events that modify the system's network environment are collected"
  blockinfile:
    path: /etc/audit/rules.d/audit.rules
    state: present
    create: yes
    block: "-a always,exit -F arch=b64 -S sethostname -S setdomainname -k system-locale\n
            -a always,exit -F arch=b32 -S sethostname -S setdomainname -k system-locale\n
            -w /etc/issue -p wa -k system-locale\n
            -w /etc/issue.net -p wa -k system-locale\n
            -w /etc/hosts -p wa -k system-locale\n
            -w /etc/sysconfig/network -p wa -k system-locale\n
            -w /etc/sysconfig/network-scripts/ -p wa -k system-locale"
  ignore_errors: yes
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.6
    - low

- name: "SCORED | 4.1.7 | PATCH | Ensure events that modify the system's Mandatory Access Controls are collected"
  blockinfile:
    path: /etc/audit/rules.d/audit.rules
    state: present
    create: yes
    block: "-w /etc/selinux/ -p wa -k MAC-policy\n
            -w /usr/share/selinux/ -p wa -k MAC-policy"
  ignore_errors: yes
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.7
    - low

- name: "SCORED | 4.1.8 | PATCH | Ensure login and logout events are collected"
  blockinfile:
    path: /etc/audit/audit.d/audit.rules
    state: present
    create: yes
    block: "-w /var/log/lastlog -p wa -k logins\n
            -w /var/run/faillock/ -p wa -k logins"
  ignore_errors: yes
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.8
    - low

- name: "SCORED | 4.1.9 | PATCH | Ensure session initiation information is collected"
  blockinfile:
    path: /etc/audit/rules.d/audit.rules
    state: present
    create: yes
    block: "-w /var/run/utmp -p wa -k session\n
            -w /var/log/wtmp -p wa -k logins\n
            -w /var/log/btmp -p wa -k logins"
  ignore_errors: yes
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.9
    - low

- name: "SCORED | 4.1.10 | PATCH | Ensure discretionary access control permission modification events are collected"
  blockinfile:
    path: /etc/audit/rules.d/audit.rules
    state: present
    create: yes
    block: "-a always,exit -F arch=b64 -S chmod -S fchmod -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_mod\n
            -a always,exit -F arch=b32 -S chmod -S fchmod -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_mod\n
            -a always,exit -F arch=b64 -S chown -S fchown -S fchownat -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_mod\n
            -a always,exit -F arch=b32 -S chown -S fchown -S fchownat -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_mod\n
            -a always,exit -F arch=b64 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod\n
            -a always,exit -F arch=b32 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod"
  ignore_errors: yes
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.10
    - low

- name: "SCORED | 4.1.11 | PATCH | Ensure unsuccessful unauthorized file access attempts are collected"
  blockinfile:
    path: /etc/audit/rules.d/audit.rules
    state: present
    create: yes
    block: "-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access\n
            -a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access\n
            -a always,exit -F arch=b64 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access\n
            -a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access"
  ignore_errors: yes
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.11
    - low

- name: "SCORED | 4.1.12 | PATCH | Ensure use of privileged commands is collected"
  command: /bin/true
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.12
    - low

- name: "SCORED | 4.1.13 | PATCH | Ensure successful file system mounts are collected"
  lineinfile:
    dest: /etc/audit/rules.d/audit.rules
    line: "-a always,exit -F arch=b32 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts"
    state: present
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.13
    - low

- name: "SCORED | 4.1.13 | PATCH | Ensure successful file system mounts are collected"
  lineinfile:
    dest: /etc/audit/rules.d/audit.rules
    line: "-a always,exit -F arch=b64 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts"
    state: present
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.13
    - low

- name: "SCORED | 4.1.14 | PATCH | Ensure file deletion events by users are collected"
  blockinfile:
    path: /etc/audit/rules.d/audit.rules
    state: present
    create: yes
    block: "-a always,exit -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 -F auid!=4294967295 -k delete\n
            -a always,exit -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 -F auid!=4294967295 -k delete"
  ignore_errors: yes
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.14
    - low

- name: "SCORED | 4.1.15 | PATCH | Ensure changes to system administration scope (sudoers) is collected"
  lineinfile:
    dest: /etc/audit/rules.d/audit.rules
    line: "-w /etc/sudoers -p wa -k scope"
    state: present
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.15
    - low

- name: "SCORED | 4.1.15 | PATCH | Ensure changes to system administration scope (sudoers) is collected"
  lineinfile:
    dest: /etc/audit/audit.rules
    line: "-w /etc/sudoers -p wa -k scope"
    state: present
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.15
    - low

- name: "SCORED | 4.1.15 | PATCH | Ensure changes to system administration scope (sudoers) is collected"
  lineinfile:
    dest: /etc/audit/rules.d/audit.rules
    line: "-w /etc/sudoers.d -p wa -k scope"
    state: present
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.15
    - low

- name: "SCORED | 4.1.16 | PATCH | Ensure system administrator actions (sudolog) are collected"
  lineinfile:
    dest: /etc/audit/rules.d/audit.rules
    line: "-w /var/log/sudo.log -p wa -k actions"
    state: present
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.16
    - low

- name: "SCORED | 4.1.17 | PATCH | Ensure kernel module loading and unloading is collected"
  blockinfile:
    path: /etc/audit/rules.d/audit.rules
    state: present
    create: yes
    block: "-w /sbin/insmod -p x -k modules\n
            -w /sbin/rmmod -p x -k modules\n
            -w /sbin/modprobe -p x -k modules\n
            -a always,exit -F arch=b64 -S init_module -S delete_module -k modules"
  ignore_errors: yes
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.17
    - low

- name: "SCORED | 4.1.18 | PATCH | Ensure the audit configuration is immutable"
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    state: present
    create: yes
    insertafter: EOF
    line: "-e 2"
  ignore_errors: yes
  tags:
    - level2
    - auditd
    - patch
    - rule_4.1.18
    - low

- name: "SCORED | 4.2.1.1 | PATCH | Ensure rsyslog Service is enabled"
  yum:
    name: rsyslogd
    state: present
  when: amazonlinux2cis_rsyslog
  tags:
    - level1
    - patch
    - rule_4.2.1.1
    - low

- name: "SCORED | 4.2.1.1 | PATCH | Ensure rsyslog Service is enabled"
  systemd:
    name: rsyslogd
    enabled: yes
  ignore_errors: yes
  when: amazonlinux2cis_rsyslog
  tags:
    - level1
    - patch
    - rule_4.2.1.1
    - low

- name: "NOTSCORED | 4.2.1.2 | PATCH | Ensure logging is configured"
  debug:
    msg: "Edit /etc/rsyslog.conf and /etc/rsyslog.d/ files as appropriate for your environment."
  tags:
    - level1
    - patch
    - rule_4.2.1.2
    - low

- name: "SCORED | 4.2.1.3 | PATCH | Ensure rsyslog default file permissions configured"
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '^\$FileCreateMode'
    line: '$FileCreateMode 0640'
    create: yes
  when: amazonlinux2cis_rsyslog
  tags:
    - level1
    - patch
    - rule_4.2.1.3
    - low

- name: "SCORED | 4.2.1.3 | PATCH | Ensure rsyslog default file permissions configured"
  find:
    paths: /etc/rsyslog.d/
    recurse: yes
    patterns: "*.conf"
  register: rsyslogd_conf_files
  when: amazonlinux2cis_rsyslog
  tags:
    - level1
    - patch
    - rule_4.2.1.3
    - low

- name: "SCORED | 4.2.1.3 | PATCH | Ensure rsyslog default file permissions configured"
  lineinfile:
    state: present
    dest: "{{ item }}"
    regexp: '^\$FileCreateMode'
    line: '$FileCreateMode 0640'
    backup: yes
  with_items: rsyslogd_conf_files.path
  ignore_errors: yes
  when:
    - amazonlinux2cis_rsyslog
    - rsyslogd_conf_files.matches >= 1
  tags:
    - level1
    - patch
    - rule_4.2.1.3
    - low

- name: "SCORED | 4.2.1.4 | PATCH | Ensure rsyslog is configured to send logs to a remote log host"
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: "^\\*\\.\\*"
    line: "*.* @@{{ amazonlinux2cis_rsyslog_loghost_address }}"
  when: amazonlinux2cis_rsyslog
  tags:
    - level1
    - patch
    - rule_4.2.1.4
    - low

- name: "NOTSCORED | 4.2.1.5 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts."
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '^\$ModLoad imtcp'
    line: '# $ModLoad imtcp'
    create: yes
  when:
    - not amazonlinux2cis_log_server
    - amazonlinux2cis_rsyslog
  tags:
    - level1
    - patch
    - rule_4.2.1.5
    - low

- name: "NOTSCORED | 4.2.1.5 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts."
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '^\$InputTCPServerRun 514'
    line: '# $InputTCPServerRun 514'
    create: yes
  when:
    - not amazonlinux2cis_log_server
    - amazonlinux2cis_rsyslog
  tags:
    - level1
    - patch
    - rule_4.2.1.5
    - low

- name: "NOTSCORED | 4.2.1.5 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts."
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '^\$ModLoad imtcp'
    line: '$ModLoad imtcp'
    create: yes
  when:
    - amazonlinux2cis_log_server
    - amazonlinux2cis_rsyslog
  tags:
    - level1
    - patch
    - rule_4.2.1.5
    - low

- name: "NOTSCORED | 4.2.1.5 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts."
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '^\$InputTCPServerRun 514'
    line: '$InputTCPServerRun 514'
    create: yes
  when:
    - amazonlinux2cis_log_server
    - amazonlinux2cis_rsyslog
  tags:
    - level1
    - patch
    - rule_4.2.1.5
    - low

- name: "SCORED | 4.2.2.1 | PATCH | Ensure syslog-ng service is enabled"
  yum:
    name: syslog-ng
    state: present
  when: amazonlinux2cis_syslog_ng
  tags:
    - level1
    - patch
    - rule_4.2.2.1
    - low

- name: "SCORED | 4.2.2.1 | PATCH | Ensure syslog-ng service is enabled"
  systemd:
    name: syslog-ng
    enabled: yes
  ignore_errors: yes
  when: amazonlinux2cis_syslog_ng
  tags:
    - level1
    - patch
    - rule_4.2.2.1
    - low

- name: "NOTSCORED | 4.2.2.2 | PATCH | Ensure logging is configured"
  debug:
    msg: "Edit the log lines in the /etc/syslog-ng/syslog-ng.conf file as appropriate for your environment."
  tags:
    - level1
    - patch
    - rule_4.2.2.2
    - low

- name: "SCORED | 4.2.2.3 | PATCH | Ensure syslog-ng default file permissions configured"
  lineinfile:
    dest: /etc/syslog-ng/syslog-ng.conf
    regexp: '^perm(0640);'
    line: '^perm(0640);'
    create: yes
  tags:
    - level1
    - patch
    - rule_4.2.2.3
    - low

- name: "NOTSCORED | 4.2.2.4 | PATCH | Ensure syslog-ng is configured to send logs to a remote log host"
  debug:
    msg: "Edit the log lines in the /etc/syslog-ng/syslog-ng.conf file as appropriate for your environment."
  tags:
    - level1
    - patch
    - rule_4.2.2.4
    - low

- name: "NOTSCORED | 4.2.2.5 | PATCH | Ensure remote syslog-ng messages are only accepted on designated log hosts"
  debug:
    msg: "Edit the log lines in the /etc/syslog-ng/syslog-ng.conf file as appropriate for your environment."
  tags:
    - level1
    - patch
    - rule_4.2.2.5
    - low

- name: "SCORED | 4.2.3 | PATCH | Ensure rsyslog or syslog-ng is installed"
  debug:
    msg: "This task was performed during rsyslog-service check: 4.2.1.1 or during syslog-ng-service check: 4.2.2.1"
  tags:
    - level1
    - patch
    - rule_4.2.3
    - low

- name: "SCORED | 4.2.4 | PATCH | Ensure permissions on all logfiles are configured"
  command: find /var/log -type f -exec chmod g-wx,o-rwx {} +
  tags:
    - level1
    - patch
    - rule_4.2.4
    - low

- name: "NOTSCORED | 4.3 | PATCH | Ensure logrotate is configured"
  debug:
    msg: "Edit /etc/logrotate.conf and /etc/logrotate.d/* to ensure logs are rotated according to site policy."
  tags:
    - level1
    - patch
    - rule_4.3
    - low
