## COPYRIGHT NOTICE - LICENSED UNDER GNU GPLV3 ##
## START COPYRIGHT NOTICE ##
# AmazonLinux2-CIS Ansible Script - Under Joint Copyright
# Copyright (C) 2019  RADSec
# Copyright (C) 2019  Glownew Group

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
## END COPYRIGHT NOTICE ##
- name: "SCORED | 3.1.1 | PATCH | Ensure IP forwarding is disabled | IPv4"
  sysctl:
    name: net.ipv4.ip_forward
    value: 0
    state: present
    reload: yes
    ignoreerrors: yes
  when: not amazonlinux2cis_is_router
  notify:
    - sysctl flush ipv4 route table
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.1.1
    - low

- name: "SCORED | 3.1.1 | PATCH | Ensure IP forwarding is disabled | IPv6"
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: 0
    state: present
    reload: yes
    ignoreerrors: yes
  when: not amazonlinux2cis_is_router
  notify:
    - sysctl flush ipv6 route table
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.1.1
    - low

- name: "SCORED | 3.1.2 | PATCH | Ensure packet redirect sending is disabled"
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_items:
    - { name: net.ipv4.conf.all.send_redirects, value: 0 }
    - { name: net.ipv4.conf.default.send_redirects, value: 0 }
  when: not amazonlinux2cis_is_router
  notify:
    - sysctl flush ipv4 route table
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.1.2
    - low

- name: "SCORED | 3.2.1 | PATCH | Ensure source routed packets are not accepted | IPv4"
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_items:
    - { name: net.ipv4.conf.all.accept_source_route, value: 0 }
    - { name: net.ipv4.conf.default.accept_source_route, value: 0 }
  notify:
    - sysctl flush ipv4 route table
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.2.1
    - low

- name: "SCORED | 3.2.1 | PATCH | Ensure source routed packets are not accepted | IPv6"
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_items:
    - { name: net.ipv6.conf.all.accept_source_route, value: 0 }
    - { name: net.ipv6.conf.default.accept_source_route, value: 0 }
  notify:
    - sysctl flush ipv6 route table
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.2.1
    - low

- name: "SCORED | 3.2.2 | PATCH | Ensure ICMP redirects are not accepted | IPv4"
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_items:
    - { name: net.ipv4.conf.all.accept_redirects, value: 0 }
    - { name: net.ipv4.conf.default.accept_redirects, value: 0 }
  notify:
    - sysctl flush ipv4 route table
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.2.2
    - low

- name: "SCORED | 3.2.2 | PATCH | Ensure ICMP redirects are not accepted | IPv6"
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_items:
    - { name: net.ipv6.conf.all.accept_redirects, value: 0 }
    - { name: net.ipv6.conf.default.accept_redirects, value: 0 }
  notify:
    - sysctl flush ipv6 route table
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.2.2
    - low

- name: "SCORED | 3.2.3 | PATCH | Ensure secure ICMP redirects are not accepted"
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_items:
    - { name: net.ipv4.conf.all.secure_redirects, value: 0 }
    - { name: net.ipv4.conf.default.secure_redirects, value: 0 }
  notify:
    - sysctl flush ipv4 route table
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.2.3
    - low

- name: "SCORED | 3.2.4 | PATCH | Ensure suspicious packets are logged"
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_items:
    - { name: net.ipv4.conf.all.log_martians, value: 1 }
    - { name: net.ipv4.conf.default.log_martians, value: 1 }
  notify:
    - sysctl flush ipv4 route table
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.2.4
    - low

- name: "SCORED | 3.2.5 | PATCH | Ensure broadcast ICMP requests are ignored"
  sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: 1
    state: present
    reload: yes
    ignoreerrors: yes
  notify:
    - sysctl flush ipv4 route table
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.2.5
    - low

- name: "SCORED | 3.2.6 | PATCH | Ensure bogus ICMP responses are ignored"
  sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: 1
    state: present
    reload: yes
    ignoreerrors: yes
  notify:
    - sysctl flush ipv4 route table
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.2.6
    - low

- name: "SCORED | 3.2.7 | PATCH | Ensure Reverse Path Filtering is enabled"
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_items:
    - { name: net.ipv4.conf.all.rp_filter, value: 1 }
    - { name: net.ipv4.conf.default.rp_filter, value: 1 }
  notify:
    - sysctl flush ipv4 route table
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.2.7
    - low

- name: "SCORED | 3.2.8 | PATCH | Ensure TCP SYN Cookies is enabled"
  sysctl:
    name: net.ipv4.tcp_syncookies
    value: 1
    state: present
    reload: yes
    ignoreerrors: yes
  notify:
    - sysctl flush ipv4 route table
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.2.8
    - low

- name: "SCORED | 3.2.9 | PATCH | Ensure IPv6 router advertisements are not accepted"
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_items:
    - { name: net.ipv6.conf.all.accept_ra, value: 0 }
    - { name: net.ipv6.conf.default.accept_ra, value: 0 }
  notify:
    - sysctl flush ipv6 route table
  when: amazonlinux2cis_ipv6_required == true
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.2.9
    - low

- name: "SCORED | 3.3.1 | PATCH | Ensure TCP Wrappers is installed"
  yum:
    name: tcp_wrappers
    state: present
  tags:
    - level1
    - patch
    - rule_3.3.1
    - low

- name: "SCORED | 3.3.2 | PATCH | Ensure /etc/hosts.allow is configured"
  template:
    src: hosts.allow.j2
    dest: /etc/hosts.allow
    owner: root
    group: root
    mode: 0644
  tags:
    - level1
    - patch
    - rule_3.3.2
    - low

- name: "SCORED | 3.3.3 | PATCH | Ensure /etc/hosts.deny is configured"
  lineinfile:
    dest: /etc/hosts.deny
    regexp: "^(#)?ALL"
    line: "ALL: ALL"
  when: amazonlinux2cis_enable_hosts_deny
  tags:
   - level1
   - patch
   - rule_3.3.3
   - medium

- name: "SCORED | 3.4.4 | PATCH | Ensure permissions on /etc/hosts.allow are configured"
  file:
    dest: /etc/hosts.allow
    owner: root
    group: root
    mode: 0644
  tags:
    - level1
    - patch
    - rule_3.4.4
    - low

- name: "SCORED | 3.3.5 | PATCH | Ensure permissions on /etc/hosts.deny are 644"
  file:
    dest: /etc/hosts.deny
    owner: root
    group: root
    mode: 0644
  tags:
    - level1
    - patch
    - rule_3.3.5
    - low

- name: "NOTSCORED | 3.4.1 | PATCH | Ensure DCCP is disabled"
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: "^(#)?install dccp(\\s|$)"
    line: "install dccp /bin/true"
    create: yes
  tags:
    - level1
    - patch
    - rule_3.4.1
    - low

- name: "NOTSCORED | 3.4.2 | PATCH | Ensure SCTP is disabled"
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: "^(#)?install sctp(\\s|$)"
    line: "install sctp /bin/true"
    create: yes
  tags:
    - level1
    - patch
    - rule_3.4.2
    - low

- name: "NOTSCORED | 3.4.3 | PATCH | Ensure RDS is disabled"
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: "^(#)?install rds(\\s|$)"
    line: "install rds /bin/true"
    create: yes
  tags:
    - level1
    - patch
    - rule_3.4.3
    - low

- name: "NOTSCORED | 3.4.4 | PATCH | Ensure TIPC is disabled"
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: "^(#)?install tipc(\\s|$)"
    line: "install tipc /bin/true"
    create: yes
  tags:
    - level1
    - patch
    - rule_3.4.4
    - low

- name: "SCORED | 3.5.1.1 | PATCH | Ensure default deny firewall policy | INPUT Policy"
  iptables:
    ip_version: ipv4
    chain: INPUT
    policy: DROP
    action: append
    state: present
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_default_deny_rule
  tags:
    - level1
    - patch
    - rule_3.5.1.1
    - medium

- name: "SCORED | 3.5.1.1 | PATCH | Ensure default deny firewall policy | OUTPUT Policy"
  iptables:
    ip_version: ipv4
    chain: OUTPUT
    policy: DROP
    action: append
    state: present
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_default_deny_rule
  tags:
    - level1
    - patch
    - rule_3.5.1.1
    - medium

- name: "SCORED | 3.5.1.1 | PATCH | Ensure default deny firewall policy | FORWARD Policy"
  iptables:
    ip_version: ipv4
    chain: FORWARD
    policy: DROP
    action: append
    state: present
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_default_deny_rule
  tags:
    - level1
    - patch
    - rule_3.5.1.1
    - medium

- name: "SCORED | 3.5.1.2 | PATCH | Ensure loopback traffic is configured | INPUT rule"
  iptables:
    ip_version: ipv4
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
    action: append
    state: present
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_loopback_rule
  tags:
    - level1
    - patch
    - rule_3.5.1.2
    - low

- name: "SCORED | 3.5.1.2 | PATCH | Ensure loopback traffic is configured | OUTPUT rule"
  iptables:
    ip_version: ipv4
    chain: OUTPUT
    out_interface: lo
    jump: ACCEPT
    action: append
    state: present
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_loopback_rule
  tags:
    - level1
    - patch
    - rule_3.5.1.2
    - low

- name: "SCORED | 3.5.1.2 | PATCH | Ensure loopback traffic is configured | 127.0.0.0/8 rule"
  iptables:
    ip_version: ipv4
    chain: INPUT
    source: 127.0.0.0/8
    jump: DROP
    action: append
    state: present
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_loopback_rule
  tags:
    - level1
    - patch
    - rule_3.5.1.2
    - low

- name: "NOTSCORED | 3.5.1.3 | PATCH | Ensure outbound and established connections are configured"
  iptables:
    ip_version: ipv4
    chain: OUTPUT
    protocol: tcp
    match: state
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_outbound_rule
  tags:
    - level1
    - patch
    - rule_3.5.1.3
    - low

- name: "NOTSCORED | 3.5.1.3 | PATCH | Ensure outbound and established connections are configured"
  iptables:
    ip_version: ipv4
    chain: OUTPUT
    protocol: udp
    match: state
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_outbound_rule
  tags:
    - level1
    - patch
    - rule_3.5.1.3
    - low

- name: "NOTSCORED | 3.5.1.3 | PATCH | Ensure outbound and established connections are configured"
  iptables:
    ip_version: ipv4
    chain: OUTPUT
    protocol: icmp
    match: state
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_outbound_rule
  tags:
    - level1
    - patch
    - rule_3.5.1.3
    - low

- name: "NOTSCORED | 3.5.1.3 | PATCH | Ensure outbound and established connections are configured"
  iptables:
    ip_version: ipv4
    chain: INPUT
    protocol: tcp
    match: state
    ctstate: ESTABLISHED
    jump: ACCEPT
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_outbound_rule
  tags:
    - level1
    - patch
    - rule_3.5.1.3
    - low

- name: "NOTSCORED | 3.5.1.3 | PATCH | Ensure outbound and established connections are configured"
  iptables:
    ip_version: ipv4
    chain: INPUT
    protocol: udp
    match: state
    ctstate: ESTABLISHED
    jump: ACCEPT
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_outbound_rule
  tags:
    - level1
    - patch
    - rule_3.5.1.3
    - low

- name: "NOTSCORED | 3.5.1.3 | PATCH | Ensure outbound and established connections are configured"
  iptables:
    ip_version: ipv4
    chain: INPUT
    protocol: icmp
    match: state
    ctstate: ESTABLISHED
    jump: ACCEPT
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_outbound_rule
  tags:
    - level1
    - patch
    - rule_3.5.1.3
    - low

- name: "SCORED | 3.5.1.4 | PATCH | Ensure firewall rules exist for all open ports"
  debug:
    msg: "Ensure firewall rules exist for all open ports"
  when: amazonlinux2cis_firewall == "iptables"
  tags:
    - level1
    - patch
    - rule_3.5.1.4
    - low

- name: "SCORED | 3.5.2.1 | PATCH | Ensure IPv6 default deny firewall policy | INPUT Policy"
  iptables:
    ip_version: ipv6
    chain: INPUT
    policy: DROP
    action: append
    state: present
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_default_deny_rule
  tags:
    - level1
    - patch
    - rule_3.5.2.1
    - medium

- name: "SCORED | 3.5.2.1 | PATCH | Ensure IPv6 default deny firewall policy | OUTPUT Policy"
  iptables:
    ip_version: ipv6
    chain: OUTPUT
    policy: DROP
    action: append
    state: present
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_default_deny_rule
  tags:
    - level1
    - patch
    - rule_3.5.2.1
    - medium

- name: "SCORED | 3.5.2.1 | PATCH | Ensure IPv6 default deny firewall policy | FORWARD Policy"
  iptables:
    ip_version: ipv6
    chain: FORWARD
    policy: DROP
    action: append
    state: present
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_default_deny_rule
  tags:
    - level1
    - patch
    - rule_3.5.2.1
    - medium

- name: "SCORED | 3.5.2.2 | PATCH | Ensure IPv6 loopback traffic is configured | INPUT rule"
  iptables:
    ip_version: ipv6
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
    action: append
    state: present
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_loopback_rule
  tags:
    - level1
    - patch
    - rule_3.5.2.2
    - low

- name: "SCORED | 3.5.2.2 | PATCH | Ensure IPv6 loopback traffic is configured | OUTPUT rule"
  iptables:
    ip_version: ipv6
    chain: OUTPUT
    out_interface: lo
    jump: ACCEPT
    action: append
    state: present
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_loopback_rule
  tags:
    - level1
    - patch
    - rule_3.5.2.2
    - low

- name: "SCORED | 3.5.2.2 | PATCH | Ensure IPv6 loopback traffic is configured | 127.0.0.0/8 rule"
  iptables:
    ip_version: ipv6
    chain: INPUT
    source: ::1
    jump: DROP
    action: append
    state: present
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_loopback_rule
  tags:
    - level1
    - patch
    - rule_3.5.2.2
    - low

- name: "NOTSCORED | 3.5.2.3 | PATCH | Ensure IPv6 outbound and established connections are configured"
  iptables:
    ip_version: ipv6
    chain: OUTPUT
    protocol: tcp
    match: state
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_outbound_rule
  tags:
    - level1
    - patch
    - rule_3.5.2.3
    - low

- name: "NOTSCORED | 3.5.2.3 | PATCH | Ensure IPv6 outbound and established connections are configured"
  iptables:
    ip_version: ipv6
    chain: OUTPUT
    protocol: udp
    match: state
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_outbound_rule
  tags:
    - level1
    - patch
    - rule_3.5.2.3
    - low

- name: "NOTSCORED | 3.5.2.3 | PATCH | Ensure IPv6 outbound and established connections are configured"
  iptables:
    ip_version: ipv6
    chain: OUTPUT
    protocol: icmp
    match: state
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_outbound_rule
  tags:
    - level1
    - patch
    - rule_3.5.2.3
    - low

- name: "NOTSCORED | 3.5.2.3 | PATCH | Ensure IPv6 outbound and established connections are configured"
  iptables:
    ip_version: ipv6
    chain: INPUT
    protocol: tcp
    match: state
    ctstate: ESTABLISHED
    jump: ACCEPT
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_outbound_rule
  tags:
    - level1
    - patch
    - rule_3.5.2.3
    - low

- name: "NOTSCORED | 3.5.2.3 | PATCH | Ensure IPv6 outbound and established connections are configured"
  iptables:
    ip_version: ipv6
    chain: INPUT
    protocol: udp
    match: state
    ctstate: ESTABLISHED
    jump: ACCEPT
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_outbound_rule
  tags:
    - level1
    - patch
    - rule_3.5.2.3
    - low

- name: "NOTSCORED | 3.5.2.3 | PATCH | Ensure IPv6 outbound and established connections are configured"
  iptables:
    ip_version: ipv6
    chain: INPUT
    protocol: icmp
    match: state
    ctstate: ESTABLISHED
    jump: ACCEPT
  when:
    - amazonlinux2cis_firewall == "iptables"
    - amazonlinux2cis_firewall_outbound_rule
  tags:
    - level1
    - patch
    - rule_3.5.2.3
    - low

- name: "SCORED | 3.5.2.4 | PATCH | Ensure IPv6 firewall rules exist for all open ports"
  debug:
    msg: "Ensure firewall rules exist for all open ports"
  when: amazonlinux2cis_firewall == "iptables"
  tags:
    - level1
    - patch
    - rule_3.5.2.4
    - low

- name: "SCORED | 3.5.3 | PATCH | Ensure iptables is installed"
  yum:
    name: iptables
    state: present
  when: amazonlinux2cis_firewall == "iptables"
  tags:
    - level1
    - patch
    - rule_3.5.3
    - low

- name: "NOTSCORED | 3.6 | PATCH | Ensure IPv6 is disabled"
  replace:
    dest: /etc/default/grub
    regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!ipv6\.disable=1)(?:")'
    replace: '\1"\2 ipv6.disable=1"'
    follow: yes
  ignore_errors: yes
  notify: generate new grub config
  when: amazonlinux2cis_ipv6_required == false
  tags:
   - level2
   - patch
   - rule_3.6
   - medium
